### ISSUE TITLE
No values/icon on default control settings

### ISSUE THREAD

**Issue by tmarti2** [nwg-piotr/nwg-panel#43]
Hi,
I'm using the default value for the control panel, but brightness value/sound value doesn't show, as well as icons.
![image](https://user-images.githubusercontent.com/32908972/112315802-c6a58f80-8caa-11eb-9762-eff5b2118085.png)
I'm I missing something ? Icons work fine in my gnome session, do I need to install something else ?
Thanks

**Comment by nwg-piotr** [comment]
If it comes to the icons: some themes don't include all of them. You can try changing your icon theme e.g. to Papirus, or simply turn on custom icons (light or dark) in the panel settings.

The sliders may not work for many reasons. First thing is to check if you've installed all dependencies. Please start the panel from the terminal and show mi the output. For everything to work, it should look something like this:

> Dependencies check: {'light': True, 'pamixer': True, 'pactl': True, 'playerctl': True, 'netifaces': True, 'pybluez': True, 'wlr-randr': True}

**Comment by tmarti2** [comment]
I'm already using the custion light icons, and papirus as a default theme.
```
Dependencies check: {'light': True, 'pamixer': True, 'pactl': True, 'playerctl': True, 'netifaces': True, 'pybluez': True, 'wlr-randr': False}
Running on sway
Display: eDP-1, position: top, layer: bottom, width: 1920, height: 20

** (nwg-panel:51453): WARNING **: 14:51:11.291: gtk-layer-shell v0.6.0 may not work on GTK v3.24.27. If you experience crashes, check https://github.com/wmww/gtk-layer-shell/blob/master/compatibility.md
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/nwg_panel/modules/controls.py", line 574, in refresh
    update_image(self.net_image, self.parent.net_icon_name, self.icon_size, self.icons_path)
AttributeError: 'PopupWindow' object has no attribute 'net_image'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/nwg_panel/modules/controls.py", line 574, in refresh
    update_image(self.net_image, self.parent.net_icon_name, self.icon_size, self.icons_path)
AttributeError: 'PopupWindow' object has no attribute 'net_image'
```
I get this when launching nwg-panel and hovering the control panel.

**Comment by nwg-piotr** [comment]
Could you check if settings if turning `Controls -> Settings -> Interface` on changes something?

![image](https://user-images.githubusercontent.com/20579136/112327099-6cf69280-8cb5-11eb-93fd-9f36deff7949.png)

**Comment by tmarti2** [comment]
Ok so the problem was because the name field was empty I guess, thanks !

**Comment by nwg-piotr** [comment]
Because the field was being declared on 3 conditions met, and 1 of them was not checked on attempt to refresh. Please confirm if this resolves the issue (temporarily). If so, we have the bug nailed, and I'll publish the fixed version tonight.
